# Generated by Django 5.0.3 on 2024-03-19 08:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('owner_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rooms', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='RoomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_users', to='room.room')),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_users', to='user.user')),
            ],
        ),
    ]
