# Generated by Django 5.0.3 on 2024-03-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='max_players',
            field=models.IntegerField(default=4),
        ),
    ]
