# Generated by Django 5.0.3 on 2024-03-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_is_active_room_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomuser',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
