# Generated by Django 5.0.3 on 2024-03-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_roomuser_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomuser',
            name='player_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
