# Generated by Django 5.0.3 on 2024-03-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_roomuser_player_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomuser',
            unique_together={('room_uuid', 'player_number')},
        ),
    ]
