# Generated by Django 5.0.3 on 2024-04-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_roomuser_unique_together'),
        ('user', '0003_user_online_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomuser',
            unique_together={('user_uuid', 'room_uuid')},
        ),
    ]
