# Generated by Django 5.0.3 on 2024-04-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_alter_roomuser_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomuser',
            unique_together=set(),
        ),
    ]
