# Generated by Django 5.0.3 on 2024-04-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_alter_roomuser_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='max_players',
        ),
    ]
