# Generated by Django 5.0.4 on 2024-04-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_remove_room_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
