# Generated by Django 5.0.3 on 2024-03-14 04:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_42', models.CharField()),
                ('otp_secret', models.CharField()),
                ('nickname', models.CharField(max_length=20)),
                ('avatar', models.CharField(null=True)),
            ],
        ),
    ]
