# Generated by Django 5.0.4 on 2024-04-11 07:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('type', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('score', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_42', models.CharField(db_index=True)),
                ('otp_secret', models.CharField()),
                ('nickname', models.CharField(db_index=True, max_length=20)),
                ('avatar', models.CharField(null=True)),
                ('message', models.CharField(default='', max_length=100)),
                ('online_status', models.DateTimeField(auto_now=True)),
                ('has_logged_in', models.BooleanField(default=False)),
                ('game_results', models.ManyToManyField(related_name='users', to='user.gameresult')),
            ],
        ),
        migrations.AddField(
            model_name='gameresult',
            name='players',
            field=models.ManyToManyField(related_name='game_result', to='user.user'),
        ),
    ]
