# Generated by Django 5.0.3 on 2024-03-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_42',
            field=models.CharField(db_index=True),
        ),
    ]
