# Generated by Django 5.0.4 on 2024-04-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
