# Generated by Django 5.0.4 on 2024-04-12 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_gameresult_win'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='players',
        ),
        migrations.AddField(
            model_name='gameresult',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_results_as_player1', to='user.user'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_results_as_player2', to='user.user'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='player3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_results_as_player3', to='user.user'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='player4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_results_as_player4', to='user.user'),
        ),
    ]
