# Generated by Django 5.0.4 on 2024-04-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_gameresult_players_gameresult_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
