# Generated by Django 5.0.3 on 2024-04-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_has_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
