# Generated by Django 5.0.4 on 2024-04-10 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0008_remove_room_max_players'),
        ('user', '0006_alter_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneVsOneGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('type', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('score_player1', models.IntegerField()),
                ('score_player2', models.IntegerField()),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_results_as_player1', to='user.user')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_results_as_player2', to='user.user')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('type', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('winner_score', models.IntegerField()),
                ('opponent_score', models.IntegerField()),
                ('last_opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_losses', to='user.user')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.room')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_wins', to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwoVsTwoGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('type', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('score_team1', models.IntegerField()),
                ('score_team2', models.IntegerField()),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.room')),
                ('team1_player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_results_as_team1_player1', to='user.user')),
                ('team1_player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_results_as_team1_player2', to='user.user')),
                ('team2_player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_results_as_team2_player1', to='user.user')),
                ('team2_player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_results_as_team2_player2', to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
