# Generated by Django 5.0.3 on 2024-04-08 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('room', '0008_remove_room_max_players'),
        ('user', '0006_alter_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamenthistory',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='tournamenthistory',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='tournamenthistory',
            name='user3',
        ),
        migrations.RemoveField(
            model_name='tournamenthistory',
            name='user4',
        ),
        migrations.RemoveField(
            model_name='winlosehistory',
            name='user_uuid',
        ),
        migrations.CreateModel(
            name='OneVsOneGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('win', models.BooleanField()),
                ('score_player1', models.IntegerField()),
                ('score_player2', models.IntegerField()),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='user.user')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='user.user')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_vs_one_game_results', to='room.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TournamentGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('win', models.BooleanField()),
                ('final_scores', models.JSONField()),
                ('players', models.ManyToManyField(related_name='tournament_results', to='user.user')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_game_results', to='room.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwoVsTwoGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('win', models.BooleanField()),
                ('score_team1', models.IntegerField()),
                ('score_team2', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_vs_two_game_results', to='room.room')),
                ('team1_player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_player1', to='user.user')),
                ('team1_player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_player2', to='user.user')),
                ('team2_player3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_player3', to='user.user')),
                ('team2_player4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_player4', to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='OneVsOneHistory',
        ),
        migrations.DeleteModel(
            name='TournamentHistory',
        ),
        migrations.DeleteModel(
            name='WinLoseHistory',
        ),
    ]
