# Generated by Django 5.0.4 on 2024-04-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onevsonegameresult',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='onevsonegameresult',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='tournamentgameresult',
            name='last_opponent',
        ),
        migrations.RemoveField(
            model_name='tournamentgameresult',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='twovstwogameresult',
            name='team1_player1',
        ),
        migrations.RemoveField(
            model_name='twovstwogameresult',
            name='team1_player2',
        ),
        migrations.RemoveField(
            model_name='twovstwogameresult',
            name='team2_player1',
        ),
        migrations.RemoveField(
            model_name='twovstwogameresult',
            name='team2_player2',
        ),
        migrations.AddField(
            model_name='onevsonegameresult',
            name='player1_avatar',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onevsonegameresult',
            name='player1_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onevsonegameresult',
            name='player2_avatar',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onevsonegameresult',
            name='player2_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournamentgameresult',
            name='last_opponent_avatar',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournamentgameresult',
            name='last_opponent_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournamentgameresult',
            name='winner_avatar',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tournamentgameresult',
            name='winner_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twovstwogameresult',
            name='team1_player1_avatar',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twovstwogameresult',
            name='team1_player1_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twovstwogameresult',
            name='team1_player2_avatar',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twovstwogameresult',
            name='team1_player2_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twovstwogameresult',
            name='team2_player1_avatar',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twovstwogameresult',
            name='team2_player1_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twovstwogameresult',
            name='team2_player2_avatar',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twovstwogameresult',
            name='team2_player2_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
