# Generated by Django 5.0.3 on 2024-04-08 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_tournamenthistory_user1_and_more'),
        ('room', '0008_remove_room_max_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onevsonegameresult',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='one_vs_one_game_results', to='room.room'),
        ),
        migrations.AlterField(
            model_name='tournamentgameresult',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_game_results', to='room.room'),
        ),
        migrations.AlterField(
            model_name='twovstwogameresult',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='two_vs_two_game_results', to='room.room'),
        ),
    ]
