# Generated by Django 5.0.4 on 2024-04-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_onevsonegameresult_player1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentGameResult',
        ),
    ]
